version: 0.2

env:
  variables:
    ENVNAME: dev
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip --version || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - git config --global user.email build@lambda-my-aws.io
      - git config --global user.name codebuild
      - pip install ecs-composex==0.1.2


  pre_build:
    commands:
      - ecs_composex --help
      - mkdir outputs

  build:
    commands:
      - ecs_composex --create-vpc --create-cluster --single-nat --bucket-name ${CFN_TPL_BUCKET} -f compose.yml -o outputs/composex_root.yml

artifacts:
  files:
    - '*'
  base-directory: outputs
