configs:
  app01:
    is_public: true
    use_alb: true
    use_nlb: false
  app02:
    use_alb: false
    use_cloudmap: true
    use_nlb: false
  app03:
    use_alb: false
    use_cloudmap: true
    use_nlb: false
  composex:
    use_exports: false
    use_ssm: false
  globals:
    network:
      use_cloudmap: true
  spot_config:
    bid_price: 0.42
    spot_instance_types:
      m5a.2xlarge:
        weight: 8
      m5a.4xlarge:
        weight: 16
      m5a.xlarge:
        weight: 4
    use_spot: true
services:
  app01:
    environment:
      NAME: DISPATCH
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-01:16
    links:
    - app03
    ports:
    - 80:80
  app02:
    environment:
      NAME: batcher
    image: nginx
  app03:
    environment:
      NAME: timeteller
    image: 373709687836.dkr.ecr.eu-west-1.amazonaws.com/blog-app-03@sha256:5951fb3dc194f814daf4e3503fd82382ed624b35667d49d9d386ed502b6754e6
    labels:
      healthcheck:
        http: 80/
      use_cloudmap: true
    ports:
    - 80:80
x-sqs:
  DLQ:
    Properties: {}
    Services:
    - access: RWMessages
      name: app02
  Queue01:
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: DLQ
        maxReceiveCount: 1
    Services:
    - access: RWPermissions
      name: app01
    Settings:
      EnvNames:
      - APP_QUEUE
      - AppQueue
x-tags:
- name: costcentre
  value: LambdaMyAws
- name: owner
  value: JohnPreston
- name: mail
  value: john@lambda-my-aws.io
